I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/rootInferno.rpy", line 34: is not terminated with a newline. (Check strings and parenthesis.)
(Perhaps you left out a " at the end of the first line.)
        "Проснулся я от брызгов солёной воды попавших мне в лицо: в море разыгрались волны, конечно, не такие большие, чтобы представлять какую-то опасность для моей лодки... Уже наступила ночь, лишь только звёзды и луна хоть как-то освещали бесконечную водную поверхность. Вокруг не виднелось даже и намёка на берег. Я вспоминал события прошедшего дня, ужасаясь от своего поступка. В тусклом лунном свете я стал рыться в разбросанных ящиках. Должно же в них быть хоть что-то, что могло бы помочь мне выбраться? Один хлам! И вообще... Эта сумашедшая китаянка затопила наш лайнер, но почему же я один на лодке в куче хлама? Выжили ли остальные? Боюсь, что я никогда не узнаю ответы на эти вопросы. А может, уже организовали спасательную экспедицию? Не мог же я далеко уплыть на этой лодке? Точно! 

Ren'Py Version: Ren'Py 6.99.6.739
