I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 85, in script
    return
Exception: Could not find return label (u'/Users/romanismagilov/Desktop/\u0423\u0447\u0435\u0308\u0431\u0430, \u043f\u0440\u043e\u0435\u043a\u0442\u044b/\u0420\u0430\u0441\u0441\u043a\u0430\u0437\u0438\u043a/Tesl/Code/game/ch3day2.rpy', 1451783577, 0).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 85, in script
    return
  File "/Applications/renpy-6.99.6-sdk/renpy/ast.py", line 1352, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "/Applications/renpy-6.99.6-sdk/renpy/execution.py", line 489, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'/Users/romanismagilov/Desktop/\u0423\u0447\u0435\u0308\u0431\u0430, \u043f\u0440\u043e\u0435\u043a\u0442\u044b/\u0420\u0430\u0441\u0441\u043a\u0430\u0437\u0438\u043a/Tesl/Code/game/ch3day2.rpy', 1451783577, 0).

Darwin-14.5.0-x86_64-i386-64bit
Ren'Py 6.99.6.739
TESL 0.0
